/**
 * Magyar szemantikus szinonima/asszociációs háló
 *
 * Minden kulcs és érték ékezet nélküli, kisbetűs (normalize()-olt).
 * A keresőmotor a beírt tokeneket kibővíti az itt található kapcsolódó szavakkal.
 */
const synonymMap = {
  // ===== EU és Brüsszel =====
  "brusszel": ["eu", "europai", "unio", "bizottsag", "europai parlament", "jogallamisag", "veto", "tagallam"],
  "eu": ["brusszel", "europai", "unio", "tagallam", "kohecios", "tamogatas", "jogallamisag", "bizottsag"],
  "europai": ["eu", "brusszel", "unio", "tagallam", "kohecios"],
  "unio": ["eu", "brusszel", "europai", "tagallam"],
  "bizottsag": ["eu", "brusszel", "europai bizottsag", "von der leyen"],
  "jogallamisag": ["eu", "brusszel", "demokracia", "jogallam", "hetes cikkely", "veto"],
  "veto": ["eu", "brusszel", "jogallamisag", "magyarorszag", "szankcio"],
  "kohecios": ["eu", "tamogatas", "unios penz", "fejlesztes"],
  "tagallam": ["eu", "brusszel", "europai", "unio"],

  // ===== Háború és biztonság =====
  "haboru": ["ukrajna", "oroszorszag", "nato", "biztonsag", "vedelmi", "fegyver", "konfliktus", "beke", "katonai"],
  "ukrajna": ["haboru", "oroszorszag", "nato", "menekultek", "szankcio", "veto", "beke", "konfliktus"],
  "oroszorszag": ["haboru", "ukrajna", "putyin", "szankcio", "gaz", "energia", "fuggoseg"],
  "nato": ["haboru", "vedelmi", "biztonsag", "katonai", "szovetseges", "hadsereg"],
  "beke": ["haboru", "ukrajna", "konfliktus", "targyalas", "diplomacia"],
  "katonai": ["nato", "haboru", "hadsereg", "vedelmi", "fegyver"],
  "fegyver": ["haboru", "katonai", "nato", "hadsereg"],
  "szankcio": ["oroszorszag", "ukrajna", "eu", "haboru", "veto"],
  "putyin": ["oroszorszag", "haboru", "ukrajna", "autoriter"],
  "konfliktus": ["haboru", "ukrajna", "beke", "katonai"],

  // ===== Gazdaság és megélhetés =====
  "draga": ["inflacio", "aremelkedes", "megelhetes", "szegeny", "ar", "dragulas", "penz"],
  "dragulas": ["inflacio", "aremelkedes", "draga", "megelhetes", "ar"],
  "inflacio": ["draga", "aremelkedes", "penzromlas", "forint", "ar", "dragulas", "megelhetes"],
  "aremelkedes": ["inflacio", "draga", "dragulas", "megelhetes"],
  "fizetes": ["ber", "minimalber", "atlagber", "kereset", "jovedelem", "netto", "brutto", "munka"],
  "ber": ["fizetes", "minimalber", "atlagber", "kereset", "netto", "brutto", "munka", "jovedelem"],
  "minimalber": ["ber", "fizetes", "kereset", "szegeny", "megelhetes"],
  "kereset": ["ber", "fizetes", "jovedelem", "netto", "brutto", "minimalber"],
  "jovedelem": ["ber", "fizetes", "kereset", "netto", "ado"],
  "netto": ["ber", "fizetes", "kereset", "brutto", "jovedelem"],
  "brutto": ["ber", "fizetes", "kereset", "netto", "jovedelem"],
  "rezsi": ["energia", "gaz", "aram", "futes", "kozmu", "szamla", "rezsicsokkentes", "villany"],
  "rezsicsokkentes": ["rezsi", "energia", "gaz", "aram", "kozmu", "kormany"],
  "lakas": ["alberlet", "ingatlan", "lakhatas", "csok", "hitel", "lakasar", "otthon"],
  "alberlet": ["lakas", "ingatlan", "lakhatas", "lakasar", "koltseg"],
  "ingatlan": ["lakas", "alberlet", "lakasar", "hitel", "csok"],
  "nyugdij": ["oregseg", "nyugdijas", "minimalnyugdij", "eloregedes", "jarulék"],
  "ado": ["szja", "afa", "jarulek", "adorendszer", "koltsegvetes", "ber", "jovedelem"],
  "szegeny": ["szegenyseg", "hatranyos", "nelkulozes", "megelhetes", "draga"],
  "szegenyseg": ["szegeny", "hatranyos", "nelkulozes", "megelhetes", "tarsadalmi"],
  "megelhetes": ["draga", "inflacio", "szegeny", "ber", "ar", "fizetes", "rezsi"],
  "forint": ["penz", "inflacio", "arfolyam", "mnb", "euro", "penzromlas", "gyengules"],
  "penz": ["forint", "gazdasag", "inflacio", "megelhetes", "koltsegvetes"],
  "ar": ["draga", "inflacio", "aremelkedes", "megelhetes", "dragulas"],
  "szar": ["rossz", "szornyuseg", "katasztrofa", "problema"],
  "gyengul": ["forint", "arfolyam", "penzromlas"],
  "elszall": ["draga", "aremelkedes", "dragulas", "megelhetes"],
  "hitel": ["bank", "lakas", "kamat", "torlesztes", "kolcson"],
  "euro": ["forint", "arfolyam", "eu", "penz"],
  "munka": ["foglalkoztatas", "munkahely", "munkanelkuliseg", "ber", "fizetes"],
  "munkanelkuli": ["munkahely", "foglalkoztatas", "szocialis", "megelhetes"],

  // ===== Egészségügy =====
  "korhaz": ["egeszsegugy", "orvos", "beteg", "varolista", "ellatas", "mutet"],
  "orvos": ["egeszsegugy", "korhaz", "orvoshiany", "haziorvos", "apolo", "ellatas"],
  "orvoshiany": ["egeszsegugy", "orvos", "apolo", "kivanorlas", "ellatas"],
  "beteg": ["egeszsegugy", "korhaz", "varolista", "gyogyszer", "ellatas"],
  "egeszsegugy": ["korhaz", "orvos", "beteg", "varolista", "gyogyszer", "apolo", "ellatas", "reform"],
  "gyogyszer": ["egeszsegugy", "beteg", "patika", "tamogatas", "ar"],
  "varolista": ["korhaz", "egeszsegugy", "mutet", "beteg", "ellatas"],
  "apolo": ["orvos", "egeszsegugy", "korhaz", "apolohiany", "ber"],
  "szetesik": ["egeszsegugy", "korhaz", "varolista", "orvoshiany", "katasztrofa", "rossz"],
  "haziorvos": ["orvos", "egeszsegugy", "rendelo", "alapellatas"],
  "mutet": ["korhaz", "varolista", "egeszsegugy", "beteg"],

  // ===== Oktatás =====
  "iskola": ["oktatas", "tanar", "diak", "tanulas", "kozoktatas", "pedagogus"],
  "tanar": ["oktatas", "pedagogus", "tanarhiany", "iskola", "ber", "sztrajk", "kozoktatas"],
  "tanarhiany": ["tanar", "oktatas", "iskola", "pedagogus", "ber", "kivanorlas"],
  "pedagogus": ["tanar", "oktatas", "iskola", "ber", "sztrajk", "tanarhiany"],
  "egyetem": ["felsooktatas", "hallgato", "alapitvany", "ceu", "tudomany"],
  "oktatas": ["iskola", "tanar", "diak", "kozoktatas", "pedagogus", "egyetem", "tanulas"],
  "diak": ["iskola", "tanar", "oktatas", "tanulas", "hallgato"],
  "hallgato": ["egyetem", "felsooktatas", "diak", "tanulas"],
  "ceu": ["egyetem", "soros", "felsooktatas", "demokracia"],
  "kozoktatas": ["iskola", "tanar", "oktatas", "diak", "pedagogus"],
  "sztrajk": ["tanar", "pedagogus", "ber", "tuntetes", "jogok"],

  // ===== Korrupció =====
  "lopas": ["korrupcio", "kozbeszerzes", "oligarcha", "kozpenz", "mutyizas"],
  "lop": ["korrupcio", "kozbeszerzes", "oligarcha", "kozpenz", "lopas", "mutyizas", "tolvaj"],
  "lopnak": ["korrupcio", "kozbeszerzes", "oligarcha", "kozpenz", "lopas", "mutyizas", "tolvaj"],
  "tolvaj": ["korrupcio", "lopas", "kozpenz", "oligarcha", "mutyizas"],
  "korrupt": ["korrupcio", "kozbeszerzes", "oligarcha", "atlathatatlan", "kozpenz"],
  "korrupcio": ["lopas", "kozbeszerzes", "oligarcha", "kozpenz", "mutyizas", "tolvaj", "atlathatatlan"],
  "kozpenz": ["korrupcio", "koltsegvetes", "kozbeszerzes", "asz", "lopas"],
  "oligarcha": ["korrupcio", "meszaros", "ner", "vagyon", "kozbeszerzes", "gazdagodas"],
  "meszaros": ["oligarcha", "korrupcio", "ner", "vagyon", "gazdagodas"],
  "ner": ["oligarcha", "korrupcio", "meszaros", "fidesz", "rendszer"],
  "stadion": ["sportfinanszrozas", "tao", "korrupcio", "koltsegvetes", "kozpenz"],
  "kozbeszerzes": ["korrupcio", "kozpenz", "oligarcha", "atlathatatlan", "tulartazas"],
  "mutyizas": ["korrupcio", "lopas", "kozbeszerzes", "kozpenz", "tolvaj"],
  "mutyi": ["korrupcio", "lopas", "kozbeszerzes", "kozpenz", "mutyizas"],
  "gazdagodas": ["oligarcha", "korrupcio", "vagyon", "meszaros"],
  "atlathatatlan": ["korrupcio", "kozbeszerzes", "transzparencia", "kozpenz"],
  "koltsegvetes": ["kozpenz", "ado", "kiadás", "kormany", "allam"],
  "politikus": ["kereset", "jovedelem", "vagyonnyilatkozat", "korrupcio", "fizetés", "parlament"],

  // ===== Demokrácia =====
  "sajto": ["media", "sajtoszabadsag", "ujsagiro", "cenzura", "propaganda"],
  "sajtoszabadsag": ["sajto", "media", "cenzura", "demokracia", "ujsagiro"],
  "szabadsag": ["demokracia", "jogallam", "emberi jogok", "sajto", "velo"],
  "demokracia": ["jogallam", "szabadsag", "valasztas", "parlament", "emberi jogok", "ellenzek"],
  "jogallam": ["demokracia", "szabadsag", "jogallamisag", "birosag", "eu"],
  "valasztas": ["szavazas", "orszaggyulesi", "kampany", "part", "demokracia"],
  "szavazas": ["valasztas", "kampany", "szavazo", "part", "demokracia"],
  "ellenzek": ["part", "valasztas", "parlament", "demokracia", "kormany"],
  "parlament": ["orszaggyules", "kepviselo", "demokracia", "torveny", "ellenzek"],
  "tuntetes": ["tiltakozas", "demokracia", "szabadsag", "sztrajk"],

  // ===== Energia =====
  "atom": ["paks", "atomenergia", "nuklearis", "eromu"],
  "paks": ["atomeromu", "rosatom", "energia", "nuklearis", "orosz"],
  "rosatom": ["paks", "oroszorszag", "nuklearis", "atom", "fuggoseg"],
  "gaz": ["orosz", "foldgaz", "energia", "fuggoseg", "rezsi", "futes"],
  "foldgaz": ["gaz", "orosz", "energia", "fuggoseg", "rezsi"],
  "megujulo": ["napenergia", "szelenergia", "zold", "klima", "kornyezet"],
  "napenergia": ["megujulo", "szelenergia", "zold", "energia"],
  "energia": ["gaz", "aram", "rezsi", "atom", "paks", "megujulo", "futes", "villany"],
  "aram": ["energia", "villany", "rezsi", "kozmu"],
  "villany": ["aram", "energia", "rezsi", "kozmu"],
  "futes": ["gaz", "rezsi", "energia", "kozmu"],
  "klima": ["kornyezet", "megujulo", "zold", "fenntarthato", "klimavaltozas"],
  "kornyezet": ["klima", "megujulo", "zold", "szennyezes"],
  "zold": ["megujulo", "klima", "kornyezet", "fenntarthato"],

  // ===== Média és propaganda =====
  "propaganda": ["media", "kozmedia", "dezinformacio", "alhir", "cenzura", "hulyit"],
  "alhir": ["dezinformacio", "propaganda", "fake news", "tenyellenorzes", "media"],
  "dezinformacio": ["alhir", "propaganda", "media", "fake news"],
  "media": ["sajto", "kozmedia", "ujsagiro", "propaganda", "cenzura", "televizio"],
  "kozmedia": ["media", "propaganda", "mtva", "kormany", "cenzura"],
  "cenzura": ["sajto", "media", "sajtoszabadsag", "propaganda", "demokracia"],
  "ujsagiro": ["sajto", "media", "sajtoszabadsag", "cenzura"],
  "hulyit": ["propaganda", "media", "dezinformacio", "alhir", "manipulacio"],
  "manipulacio": ["propaganda", "media", "hulyit", "dezinformacio"],
  "televizio": ["media", "kozmedia", "propaganda", "mtva"],
  "mtva": ["kozmedia", "media", "propaganda", "kormany"],

  // ===== Politikai köznyelvi kifejezések =====
  "migrans": ["bevandorlas", "menekultek", "hatarkerites", "kvota", "menedekkero"],
  "bevandorlas": ["migrans", "menekultek", "hatarkerites", "kvota"],
  "menekultek": ["migrans", "bevandorlas", "ukrajna", "hatarkerites"],
  "soros": ["ceu", "civil", "ngo", "kulfoldi", "alapitvany"],
  "orban": ["kormany", "fidesz", "miniszterelnok", "kormanyfo"],
  "kormany": ["kormanyzas", "kabinet", "miniszterium", "fidesz", "orban", "miniszterelnok"],
  "fidesz": ["kormany", "orban", "part", "kormanypart"],
  "ellenzeki": ["ellenzek", "part", "demokracia", "parlament"],
  "part": ["politika", "valasztas", "fidesz", "ellenzek", "parlament"],

  // ===== Szociális ügyek =====
  "hajlektalan": ["szocialis", "szegenyseg", "lakhatas", "hajlektalansag"],
  "roma": ["hatranyos", "kisebbseg", "diszkriminacio", "szegregacio"],
  "diszkriminacio": ["roma", "kisebbseg", "egyenloseg", "jogok"],
  "civil": ["ngo", "tarsadalom", "onkenetes", "civilszervezet"],
  "ngo": ["civil", "tarsadalom", "soros", "civilszervezet"],

  // ===== Érzelmekkel terhelt köznyelvi kifejezések =====
  "katasztrofa": ["rossz", "problema", "valsag", "szetesik"],
  "rossz": ["katasztrofa", "problema", "szetesik", "szar"],
  "valsag": ["katasztrofa", "problema", "rossz", "osszeomlás"],
  "szornyuseg": ["katasztrofa", "rossz", "problema"],
  "csod": ["koltsegvetes", "gazdasag", "valsag", "allamcsod"],
  "kivanorlas": ["egeszsegugy", "orvos", "tanar", "ber", "kulfoldi munka"],
  "kulfoldi munka": ["kivanorlas", "elvanorlas", "ber", "fizetes"],
  "igazsagtalan": ["egyenlotlenseg", "szegenyseg", "korrupcio"],

  // ===== Kiegészítő témaszavak =====
  "birosag": ["jogallam", "demokracia", "igazsagszolgaltatas", "ugyeszseg"],
  "ugyeszseg": ["birosag", "jogallam", "korrupcio", "nyomozas"],
  "rendorseg": ["biztonsag", "bunmegeloz", "kozbizonsag"],
  "hatar": ["hatarkerites", "migrans", "szerbia", "bevandorlas"],
  "hatarkerites": ["migrans", "bevandorlas", "hatar", "menekultek"],
  "vagyonnyilatkozat": ["politikus", "korrupcio", "atlathatatlan", "vagyon"],
  "transzparencia": ["atlathato", "korrupcio", "kozpenz", "kozbeszerzes"],
  "nepszavazas": ["valasztas", "demokracia", "szavazas", "reszvetel"],
  "szegregacio": ["roma", "hatranyos", "oktatas", "diszkriminacio"],
  "digitalizacio": ["internet", "technologia", "fejlesztes", "oktatas"],
  "agyelszivas": ["kivanorlas", "fiatalok", "kulfoldi", "tudomany", "egyetem"],
  "kutatás": ["tudomany", "egyetem", "fejlesztes", "innovacio"],
  "videk": ["falu", "elmaradottsag", "fejlesztes", "hatranyos"],
  "budapest": ["fovaros", "videk", "centralizacio"],
  "onkormanyzat": ["helyi", "polgarmester", "helyi kormany", "koltsegvetes"],
}

export default synonymMap
