# Használat:
# pip install sentence-transformers
# python scripts/generate-embeddings.py
#
# Ez a script a fejlesztő gépén fut EGYSZER, nem a felhasználó telefonján.
# A generált vektorok bekerülnek a JSON-be és egy JS modulba.

import json
import os
import re
from sentence_transformers import SentenceTransformer

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'public', 'qa-database.json')
TERM_EMB_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'lib', 'term-embeddings.js')
SYNONYM_MAP_PATH = os.path.join(os.path.dirname(__file__), '..', 'src', 'lib', 'synonym-map.js')

PRECISION = 5  # decimal places for rounding


def extract_synonym_terms(path):
    """Extract all unique terms from synonym-map.js"""
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()

    terms = set()
    # Match all quoted strings in the JS file
    for match in re.findall(r'"([^"]+)"', content):
        # Skip comments and non-term strings
        if match.startswith('//') or match.startswith('==='):
            continue
        terms.add(match)

    return sorted(terms)


def round_vec(vec, precision=PRECISION):
    return [round(float(x), precision) for x in vec]


def main():
    print('BAAI/bge-m3 modell betöltése...')
    model = SentenceTransformer('BAAI/bge-m3')

    # === 1. Question embeddings ===
    print(f'Adatbázis betöltése: {DB_PATH}')
    with open(DB_PATH, 'r', encoding='utf-8') as f:
        db = json.load(f)

    questions = db['questions']
    print(f'{len(questions)} kérdés feldolgozása...')

    texts = []
    for q in questions:
        parts = [q['question']]
        parts.extend(q.get('tags', []))
        parts.extend(q.get('synonyms', []))
        texts.append(' '.join(parts))

    print('Kérdés-embeddings generálása...')
    q_embeddings = model.encode(texts, show_progress_bar=True, normalize_embeddings=True)

    dim = q_embeddings.shape[1]
    print(f'Embedding dimenzió: {dim}')

    for i, q in enumerate(questions):
        q['embedding'] = round_vec(q_embeddings[i])

    print(f'Adatbázis mentése: {DB_PATH}')
    with open(DB_PATH, 'w', encoding='utf-8') as f:
        json.dump(db, f, ensure_ascii=False, indent=2)

    # === 2. Term embeddings ===
    print(f'\nSzinonima-térkép betöltése: {SYNONYM_MAP_PATH}')
    terms = extract_synonym_terms(SYNONYM_MAP_PATH)
    print(f'{len(terms)} egyedi kifejezés a szótárban')

    print('Kifejezés-embeddings generálása...')
    t_embeddings = model.encode(terms, show_progress_bar=True, normalize_embeddings=True)

    # Write as JS module
    print(f'Term embeddings mentése: {TERM_EMB_PATH}')
    lines = [
        '// Auto-generated by scripts/generate-embeddings.py',
        '// DO NOT EDIT — regenerate with: python scripts/generate-embeddings.py',
        f'// Model: BAAI/bge-m3, dimension: {dim}, terms: {len(terms)}',
        '',
        'const termEmbeddings = {',
    ]

    for i, term in enumerate(terms):
        vec_str = json.dumps(round_vec(t_embeddings[i]))
        lines.append(f'  {json.dumps(term)}: {vec_str},')

    lines.append('}')
    lines.append('')
    lines.append('export default termEmbeddings')
    lines.append('')

    with open(TERM_EMB_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    # Stats
    db_size = os.path.getsize(DB_PATH) / 1024 / 1024
    term_size = os.path.getsize(TERM_EMB_PATH) / 1024 / 1024
    print(f'\nKész!')
    print(f'  qa-database.json: {db_size:.1f} MB')
    print(f'  term-embeddings.js: {term_size:.1f} MB')
    print(f'  Embedding dimenzió: {dim}')
    print(f'  Kérdések: {len(questions)}')
    print(f'  Kifejezések: {len(terms)}')


if __name__ == '__main__':
    main()
